language: node_js
node_js:
- '4'
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester eslint eslint-plugin-html
- bower install
- polylint
- eslint *.html test/*.html
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: UnwbVWKkE3dCkklaS+PbGFiz0lmKf9giLjRR61KK3jiY32Q3cD/krPOtfdsmv5+3uNNnITc8+JIg7JAeqPkLNiAZnsPyjMiiXi+isXkx30ic4YYWxBfiLrbl2+H17OEpMnqgdLEYL7FyBLtKVKlsMtJVQxiQWxhKsIWyCSVPbOu7CU1lG9gHt+FPlFApIpopiBHUufMiL6+dibdu4fODLLmCJvrU/o1wlMGYzPxfY3BbyIdqnhIXaI+xKqusr4DNNeCQtxyCxfel4Emryh6+HuhobSPkYl0P/w9NHql9CPKtUfPo83rvNSZ3Ie/Rg40WWR4SM3Dw9pFWHKHgu7xDF3jOZQFVva72jtsgGd2jgWYlYejX5Zw6KhkHeDyAG63vn+S6q8236PPXAIozwvO8cAv2vnDSyO+IGgBsYWBC3pniPr3Suh6+Cx9Yn8nG/iH4M1mtV9a7gZQEP1S/czE1PprHmaL2lzvtIL8BoKNzRPqAiM5ENxDnb+yi+vD7DatRhX+8dHh+Utv9CK+34Najq/vt4t7i3Z5TUTcl/AR5VudHhrtKWIe7kn6J3sbIXVSjfa0gFdSCklT/3HWdNd4j3ysl5/x3hOn8y413oamdJKoWKcjJamNfyAbYo3RbpB/ktgE4X0P/J+f3gm0dp0WHPV1bWjYVXgNfK5dr/SXLc1I=
  - secure: jHCYXgSARp5d8ghOD3lsG6HWcEzU8h8ie9uZxo3MXVe/fD6EmNEmP+7i6gF81qSc6wTU2UGmUz86VDHc10PY6/Ki2zefX0rc26MVITc0iPQT1AQgMgyftv+ibivko5YemOQbQCGdogfuiS3ZC4RZfhzUMEpI9IOhalUrXram0Gts7ZVXKqpM5VP3TpOWXeA8+u93e0SMH1MAWbReiokfV0YBfhRouXESjLBjg4/bf6Vb/UrPdNkyGDOx3YUu0gqPhDANU1YkjqIeIABOwV541X5mQ1BTx5LIFZQpzDiRfk8iKQiKcxcjXCOAMRgqdk1jCGx93WXx3a347jz3sl0wHBS6Gpaba9W0zuTJsGM6sJf5Yn6fMvP8Da6L3OlBUOhBPECRGoXn9ABmPGEDwBrERDnkxW0ZytGd5Y4y//3d6Zo1qkx4h3a4DuDwmL8PZt7WQza4C3+q9Uavov1TygevYBky0eKtoDVzzqLX2XhSYwYwpSFuhHtH7kYQqCaSS3sLXTzt5SkINcnQIzeIPXs4qOszX3uF/JAwgyn9u6qcGyeTGtCdOeHrMdv6lPFUbV0ImycgHpnkvszo0hZWvw5UAkM6pMYe8mOcAhqDvF9ROGxUkJlANe6B9XZFzz77v6AjmWMWq8mi3NRsDorLid/DoG5HDGhetyEapsE+mIAFJzI=
